apiVersion: v1
kind: Service
metadata:
  name: {{ include "tessio.fullname" . }}-api
  labels: {{- include "tessio.labels" . | nindent 4 }}
spec:
  selector: {{- include "tessio.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: 3000
      targetPort: http
