{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tessio.postgres.fullname" . }}
  labels: {{- include "tessio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tessio.postgres.fullname" . }}
  replicas: 1
  selector:
    matchLabels: {{- include "tessio.componentSelectorLabels" (dict "ctx" . "component" "postgresql") | nindent 6 }}
  template:
    metadata:
      labels: {{- include "tessio.componentSelectorLabels" (dict "ctx" . "component" "postgresql") | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tessio.postgres.fullname" . }}
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.auth.username | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgresql.auth.username | quote }}]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources: {{- toYaml .Values.postgresql.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgresql.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}
