{{- if .Values.postgresql.enabled }}
{{- $sec := lookup "v1" "Secret" .Release.Namespace (printf "%s-postgresql" (include "tessio.fullname" .)) -}}
{{- $data := (default (dict) (and $sec $sec.data)) -}}
{{- $pw := .Values.postgresql.auth.password | default (get $data "POSTGRES_PASSWORD" | default "" | b64dec) | default (randAlphaNum 24) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tessio.postgres.fullname" . }}
  labels: {{- include "tessio.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ $pw | quote }}
{{- end }}
