apiVersion: v1
kind: Service
metadata:
  name: {{ include "tessio.fullname" . }}-runner
  labels: {{- include "tessio.labels" . | nindent 4 }}
spec:
  selector: {{- include "tessio.componentSelectorLabels" (dict "ctx" . "component" "runner") | nindent 4 }}
  ports:
    - name: http
      port: 3100
      targetPort: http
