{{- if not .Values.secrets.existingSecret }}
{{- $sec := lookup "v1" "Secret" .Release.Namespace (include "tessio.secretName" .) -}}
{{- $data := (default (dict) (and $sec $sec.data)) -}}
{{- $session := .Values.secrets.sessionSecret | default (get $data "SESSION_SECRET" | default "" | b64dec) | default (randAlphaNum 48) -}}
{{- $key := .Values.secrets.secretKey | default (get $data "TESSIO_SECRET_KEY" | default "" | b64dec) | default (randAlphaNum 32 | b64enc) -}}
{{- $runnerToken := .Values.secrets.runnerToken | default (get $data "RUNNER_TOKEN" | default "" | b64dec) | default (randAlphaNum 48) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tessio.secretName" . }}
  labels: {{- include "tessio.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ $session | quote }}
  TESSIO_SECRET_KEY: {{ $key | quote }}
  RUNNER_TOKEN: {{ $runnerToken | quote }}
  {{- if and .Values.admin.email .Values.admin.password }}
  TESSIO_ADMIN_EMAIL: {{ .Values.admin.email | quote }}
  TESSIO_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}
  TESSIO_ADMIN_NAME: {{ .Values.admin.name | quote }}
  {{- end }}
{{- end }}
